---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tags: 3.5.3-jdk-8-alpine
inputs:
  - name: src
caches:
  - path: src/m2
run:
  path: bash
  args:
    - -c
    - |
      set -e
      cd src
      rm -rf ~/.m2
      ln -fs $(pwd)/m2 ~/.m2
      mvn --version
      java -version
      mvn package
