---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tags: 3.5.3-jdk-8-alpine
inputs:
  - name: src
outputs:
  - name: target
caches:
  - path: src/m2
run:
  path: bash
  args:
    - -c
    - |
      set -e
      #cd src
      #rm -rf ~/.m2
      #ln -s $(pwd)/m2 ~/.m2
      du -hs src/m2
      mvn --version
      java -version
      #mvn package
      mvn verify -Dmaven.repo.local=src/m2 -f src
      cp -r src/target .
