---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tags: 3.5.3-jdk-8-alpine
inputs:
  - name: src
caches:
  - path: src/m2
run:
  path: bash
  args:
    - -c
    - |
      set -e
      mvn verify -Dmaven.repo.local=src/m2 -f src
