---
resources:
- name: src
  type: git
  source:
    uri: https://github.com/yoshizo/concourse-study
    branch: master
    username: ((GIT_USERNAME))
    password: ((GIT_PASSWORD))
- name: api
  type: s3
  source:
    bucket: releases
    regexp: sample-app/18.05.00.0000/sample-app-(.*).jar
    access_key_id: ACCESS_KEY_ID
    secret_access_key: SECRET_ACCESS_KEY
    endpoint: localstack.example.com:4572
    region_name: us-east-1
    disable_ssl: true
- name: api-image
  type: docker-image
  source:
    repository: yoshizo55/sample-app-api
    email: ((EMAIL))
    username: ((DOCKER_USERNAME))
    password: ((DOCKER_PASSWORD))
#- name: batch
#  type: s3
#  source:
#    bucket: releases
#    regexp: sample-app/18.05.00.0000/sample-app-batch-(.*).jar
#    access_key_id: ACCESS_KEY_ID
#    secret_access_key: SECRET_ACCESS_KEY
#- name: front
#  type: s3
#  source:
#    bucket: releases
#    regexp: sample-app/18.05.00.0000/sample-app-(.*).war
#    access_key_id: ACCESS_KEY_ID
#    secret_access_key: SECRET_ACCESS_KEY
#- name: typelayout
#  type: s3
#  source:
#    bucket: releases
#    regexp: sample-app/18.05.00.0000/sample-app-typelayout-(.*).zip
#    access_key_id: ACCESS_KEY_ID
#    secret_access_key: SECRET_ACCESS_KEY
#- name: autoindex
#  type: s3
#  source:
#    bucket: releases
#    regexp: sample-app/18.05.00.0000/sample-app-autoindex-(.*).jar
#    access_key_id: ACCESS_KEY_ID
#    secret_access_key: SECRET_ACCESS_KEY
#- name: sql
#  type: s3
#  source:
#    bucket: releases
#    regexp: sample-app/18.05.00.0000/sample-app-sql-(.*).zip
#    access_key_id: ACCESS_KEY_ID
#    secret_access_key: SECRET_ACCESS_KEY

#- name: base-image
#  type: docker-image
#  source:
#    repository: tomcat
#    tags: 8.5.30-jre8-slim

#- name: front-image
#  type: docker-image
#  source:
#    repository: yoshizo55/sample-app
#    email: ((EMAIL))
#    username: ((DOCKER_USERNAME))
#    password: ((DOCKER_PASSWORD))

#- name: mysql-schema
#  type: docker-image
#  source:
#    repository: concourse/git-resource
#
#- name: mysql-data
#  type: docker-image
#  source:
#    repository: concourse/git-resource
#
#- name: elasticsearch-index
#  type: docker-image
#  source:
#    repository: concourse/git-resource
#
#- name: elasticsearch-data
#  type: docker-image
#  source:
#    repository: concourse/git-resource

jobs:
- name: maven-build
  plan:
  - get: src
    #  trigger: true
  - task: build
    file: src/ci/build.yml
  - put: api
    params:
      file: target/sample-app-*.jar
      acl: public-read
- name: docker-build
  plan:
  - get: src
  - get: api
  - put: api-image
    params:
      build: src/ci
      build_args:
        JAR_FILE: sample-app-*.jar
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker_image
        source:
          repository: yoshizo55/sample-app
      run:
        path: true
